#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
  path: /api/authentication_token
  methods: ['POST']

swagger_ui:
  path: /docs
  controller: api_platform.swagger.action.ui